######################################################################
# Automatically generated by qmake (3.0) Tue May 10 12:08:27 2016
######################################################################

TEMPLATE = app
TARGET = baseroulanteV5
INCLUDEPATH += . /usr/include/libusb-1.0/ /usr/local/include/libfreenect /usr/include/libdrm /usr/include/opencv
# Input
HEADERS += Adafruit_ADS1015.h \
           analogInput.h \
           AStar.h \
           AX13.h \
           baseroulante.h \
           buzzer.h \
           canne.h \
           capteurForce.h \
           capteurpresence.h \
           CcapteurIR.h \
           cgps.h \
           joystick.h \
           kangaroo.h \
           lidarLite.h \
           relay.h \
           roblind.h \
           serialport.h \
           vibreur.h \
    Grille.h \
    Kinect.h
SOURCES += Adafruit_ADS1015.cpp \
           analogInput.cpp \
           AStar.cpp \
           AX13.cpp \
           baseroulante.cpp \
           buzzer.cpp \
           canne.cpp \
           capteurForce.cpp \
           capteurpresence.cpp \
           CcapteurIR.cpp \
           cgps.cpp \
           joystick.cpp \
           kangaroo.cpp \
           lidarLite.cpp \
           main.cpp \
           relay.cpp \
           roblind.cpp \
           serialport.cpp \
           vibreur.cpp \
    Grille.cpp \
    Kinect.cpp

LIBS += -L/usr/local/include -lwiringPi -lpthread -lusb
LIBS += -L/usr/local/lib -lGL -lfreenect /usr/lib/arm-linux-gnueabihf/libopencv_calib3d.so -lopencv_calib3d /usr/lib/arm-linux-gnueabihf/libopencv_contrib.so -lopencv_contrib /usr/lib/arm-linux-gnueabihf/libopencv_core.so -lopencv_core /usr/lib/arm-linux-gnueabihf/libopencv_features2d.so -lopencv_features2d /usr/lib/arm-linux-gnueabihf/libopencv_flann.so -lopencv_flann /usr/lib/arm-linux-gnueabihf/libopencv_gpu.so -lopencv_gpu /usr/lib/arm-linux-gnueabihf/libopencv_highgui.so -lopencv_highgui /usr/lib/arm-linux-gnueabihf/libopencv_imgproc.so -lopencv_imgproc /usr/lib/arm-linux-gnueabihf/libopencv_legacy.so -lopencv_legacy /usr/lib/arm-linux-gnueabihf/libopencv_ml.so -lopencv_ml /usr/lib/arm-linux-gnueabihf/libopencv_objdetect.so -lopencv_objdetect /usr/lib/arm-linux-gnueabihf/libopencv_ocl.so -lopencv_ocl /usr/lib/arm-linux-gnueabihf/libopencv_photo.so -lopencv_photo /usr/lib/arm-linux-gnueabihf/libopencv_stitching.so -lopencv_stitching /usr/lib/arm-linux-gnueabihf/libopencv_superres.so -lopencv_superres /usr/lib/arm-linux-gnueabihf/libopencv_ts.so -lopencv_ts /usr/lib/arm-linux-gnueabihf/libopencv_video.so -lopencv_video /usr/lib/arm-linux-gnueabihf/libopencv_videostab.so -lopencv_videostab -lusb
